name: Github-Workflow

on:
workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Say Hello
      run: echo "Hello, ${{github.actor}}! This is your first Github Action"

    - name: show current directory
      run: pwd
    
    - name: list all files
      run: ls -la